@startuml
interface ITransaction {
    Commit() : void
    Rollback() : void
    GetStatus() : Status
}
enum Status {
    OPEN,
    PENDING,
    ROLLEDBACK,
    COMMITTED,
    CLOSED,
    ROLEBACK_PENDING,
    COMMIT_PENDING,
}
ITransaction +-- Status
@enduml
