@startuml
class TransactionManager {
    + Commit(transaction:ITransaction) : void
    + CreateTransaction() : ITransaction
    + CurrentTransaction() : ITransaction
    + Rollback(transaction:ITransaction) : void
}
ITransactionManager <|-- TransactionManager
@enduml
