@startuml
interface ICompilerContext {
    Register(entity:object) : void
    RegisterNewObject(id:long, entity:object) : void
    Unregister(entity:object) : void
    Visited(entity:object, horizon:int) : bool
    VisitedNode(entity:object) : NodeBuilder?
    VisitedRelationshipEntity(id:long) : bool
}
ICompilerContext --> "Compiler" MultiStatementCypherCompiler
@enduml
