@startuml
interface IUpdateCypherGenerator {
    CreateCreateOperation(entity:TEntity, depth:int) : string
    CreateSetOperation(entity:TEntity, depth:int) : string
    CreateDeleteOperation(entity:TEntity, depth:int) : string
}
@enduml
