@startuml
class MissingStartNodeAttributeException {
    + MissingStartNodeAttributeException()
    + MissingStartNodeAttributeException(message:string?)
    + MissingStartNodeAttributeException(message:string?, innerException:Exception?)
}
Exception <|-- MissingStartNodeAttributeException
@enduml
