@startuml
class MissingEndNodeAttributeException {
    + MissingEndNodeAttributeException()
    + MissingEndNodeAttributeException(message:string?)
    + MissingEndNodeAttributeException(message:string?, innerException:Exception?)
}
Exception <|-- MissingEndNodeAttributeException
@enduml
