@startuml
class EntityGraphMapper {
    + EntityGraphMapper(metadata:MetaData, mappingContext:MappingContext)
    + Map(entity:object, depth:int) : ICompilerContext
    + CompilerContext() : ICompilerContext
}
class RelationshipNodes {
    + RelationshipNodes(source:object, target:object, startNodeType:Type, endNodeType:Type)
}
IEntityMapper <|-- EntityGraphMapper
EntityGraphMapper +-- RelationshipNodes
@enduml
