@startuml
class Node {
    + Label : string? <<get>> <<init>>
    + Node(label:string?)
    + AddRelationship(type:string, relationship:IRelationship) : void
}
class "Dictionary`2"<T1,T2> {
}
INode <|-- Node
Node --> "Relationships<string,IRelationship>" "Dictionary`2"
@enduml
